trainer:
  gpus: 1
  max_epochs: 750
  log_every_n_steps: 25
  check_val_every_n_epoch: 10
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss_epoch
        mode: min
        save_last: true
        filename: "gaitgraph-oumvlp-{epoch:02d}-{val_loss_epoch:.2f}"
    - class_path: pytorch_lightning.callbacks.StochasticWeightAveraging
      init_args:
        device: cuda
model:
  backend_name: resgcn-n51-r4
  learning_rate: 0.005
  loss_temperature: 0.01
  embedding_layer_size: 128
data:
  data_path: "../data"
  dataset_path: "../../datasets/OUMVLP-Pose"
  keypoints: openpose
  batch_size: 768
  num_workers: 8
  sequence_length: 30
