model:
  backend_name: resgcn-n51-r4
  tta: False
  multi_input: False
data:
  keypoints: alphapose
  multi_input: False
  flip_sequence_p: 0
  flip_lr_p: 0
  joint_noise: 0
  point_noise: 0
  random_move: 0
